# Generated by Django 5.2.7 on 2025-10-20 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('appointment_new', 'Novo Agendamento'), ('appointment_confirmed', 'Agendamento Confirmado'), ('appointment_cancelled', 'Agendamento Cancelado'), ('payment_received', 'Pagamento Recebido'), ('commission_generated', 'Comissão Gerada'), ('stock_low', 'Estoque Baixo'), ('stock_out', 'Produto Sem Estoque'), ('customer_new', 'Novo Cliente'), ('system', 'Sistema')], max_length=50, verbose_name='Tipo de Notificação')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(help_text='Conteúdo da notificação', verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, help_text='Indica se a notificação foi lida pelo usuário', verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, help_text='Data e hora em que a notificação foi lida', null=True, verbose_name='Lida em')),
                ('reference_type', models.CharField(blank=True, help_text='Ex: appointment, payment, product', max_length=50, null=True, verbose_name='Tipo de Referência')),
                ('reference_id', models.CharField(blank=True, help_text='ID do objeto relacionado', max_length=100, null=True, verbose_name='ID da Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.tenant', verbose_name='Empresa')),
                ('user', models.ForeignKey(help_text='Usuário que receberá a notificação', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'user', 'is_read'], name='notificatio_tenant__5bddd7_idx'), models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__b302ab_idx'), models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx')],
            },
        ),
    ]
