"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import os
# Adiciona imports para Supabase
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Carrega variáveis do .env
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="django-insecure-k4=h7qk_f_dqb@p(qm)&5t9+&+!q_5h=soc2yiakgari$(5w--")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# =============================================================================
# SENTRY CONFIGURATION
# =============================================================================
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

SENTRY_DSN = config('SENTRY_DSN', default='')
SENTRY_ENVIRONMENT = config('SENTRY_ENVIRONMENT', default='development')
SENTRY_RELEASE = config('SENTRY_RELEASE', default='dev')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                # Captura SQL queries para debug de performance
                transaction_style='url',
                middleware_spans=True,
                signals_spans=True,
                cache_spans=True,
            ),
        ],
        # Performance Monitoring
        traces_sample_rate=1.0 if DEBUG else 0.1,
        
        # Envia dados do usuário (email, username)
        send_default_pii=True,
        
        # Ambiente (development, staging, production)
        environment=SENTRY_ENVIRONMENT,
        
        # Versão da aplicação (útil para rastrear quando bugs foram introduzidos)
        release=SENTRY_RELEASE,
        
        # Em desenvolvimento, mostra mais detalhes no console
        debug=DEBUG,
        
        # Ignora erros comuns que não são problemas
        ignore_errors=[
            # Erros de conexão do cliente (não podemos controlar)
            'ConnectionResetError',
            'BrokenPipeError',
            # Token expirado é esperado
            'rest_framework_simplejwt.exceptions.TokenError',
        ],
        
        # Adiciona contexto global
        before_send=lambda event, hint: {
            **event,
            'tags': {
                **event.get('tags', {}),
                'server_type': 'django',
            }
        },
    )
    print(f"✅ Sentry inicializado: {SENTRY_ENVIRONMENT} (Release: {SENTRY_RELEASE})")
else:
    print("⚠️ Sentry DSN não configurado - Monitoramento de erros desabilitado")

# SENTRY API CREDENTIALS (para System Health Dashboard)
# =============================================================================
SENTRY_AUTH_TOKEN = config('SENTRY_AUTH_TOKEN', default='')
SENTRY_ORG_SLUG = config('SENTRY_ORG_SLUG', default='')
SENTRY_PROJECT_SLUG = config('SENTRY_PROJECT_SLUG', default='')

# RAILWAY API CREDENTIALS (para Infrastructure Monitoring)
# =============================================================================
RAILWAY_API_TOKEN = config('RAILWAY_API_TOKEN', default='')

# UPTIMEROBOT API CREDENTIALS (para Uptime Monitoring)
# =============================================================================
UPTIMEROBOT_API_KEY = config('UPTIMEROBOT_API_KEY', default='')

# =============================================================================# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Necessário para allauth
    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",  # Necessário para dj-rest-auth
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.microsoft",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # Local apps
    "core",
    "scheduling",
    "financial",
    "customers",
    "inventory",
    "commissions",
    "notifications",
    "payments",  # Payments & Mercado Pago Integration
    "superadmin",  # Super Admin Dashboard
    "pos",  # Point of Sale
    "goals",  # Goals and Targets
    "system_health",  # System Health Monitoring
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise - servir arquivos estáticos
    "corsheaders.middleware.CorsMiddleware",  # CORS - deve vir antes do CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.cache_middleware.CacheMiddleware",  # Cache inteligente de API responses
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Allauth middleware
    "core.middleware.TenantMiddleware",  # Middleware personalizado para Multi-Tenant
    "core.middleware.SubscriptionMiddleware",  # Trial Guard - verifica status da assinatura
    "core.sentry_middleware.SentryContextMiddleware",  # Adiciona contexto ao Sentry
    "system_health.middleware.OnlineUsersMiddleware",  # Rastreia usuários online
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuração do banco - PostgreSQL em produção, SQLite em desenvolvimento
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # SQLite para desenvolvimento local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR.parent / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Validação de senhas simplificada para desenvolvimento
# Em produção, use validadores mais rigorosos
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 6,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise - Servir arquivos estáticos em produção
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Reduzido de 100 para 20 para melhor performance
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    # THROTTLE TEMPORARIAMENTE DESABILITADO - causava erro de comparação str/float
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle'
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '100/hour',
    #     'user': '1000/hour'
    # },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_LIFETIME', default=60, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=config('JWT_REFRESH_TOKEN_LIFETIME', default=1440, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('JWT_SECRET_KEY', default=SECRET_KEY),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:3002,http://127.0.0.1:3002,https://vrb-erp-frontend.vercel.app'
).split(',')

CORS_ALLOW_CREDENTIALS = True

# CSRF Configuration - Permitir origens confiáveis
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,https://vrb-erp-frontend.vercel.app,https://*.railway.app'
).split(',')

# Permitir cookies CSRF em produção
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False  # Permitir JavaScript acessar (para React)
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'


# =============================================================================
# Storage: Cloudflare R2 (S3 Compatible)
# =============================================================================
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='auto')
AWS_S3_ADDRESSING_STYLE = 'virtual'  # Cloudflare R2 requer addressing virtual
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_DEFAULT_ACL = None

# =============================================================================
# Cache: Redis (Upstash REST API)
# =============================================================================
# Upstash Redis via REST API (funciona melhor em ambientes serverless)
UPSTASH_REDIS_REST_URL = config('UPSTASH_REDIS_REST_URL', default='')
UPSTASH_REDIS_REST_TOKEN = config('UPSTASH_REDIS_REST_TOKEN', default='')

if UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN:
    CACHES = {
        'default': {
            'BACKEND': 'core.cache_backend.UpstashRedisCache',
            'LOCATION': UPSTASH_REDIS_REST_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'upstash_redis.Redis',
            }
        }
    }
    print("✅ Cache: Upstash Redis REST")
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
    print("⚠️ Cache: LocMemCache (fallback)")

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@myerp.com')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Padrão do Django
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth
]

# Configurações do allauth
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Nosso modelo não usa username

# Configurações modernas do allauth (removendo deprecations)
ACCOUNT_LOGIN_METHODS = {'email'}  # Substitui ACCOUNT_AUTHENTICATION_METHOD
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Substitui EMAIL_REQUIRED e USERNAME_REQUIRED
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # 'mandatory' para produção
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'

# Configuração de providers (chaves serão configuradas no admin)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID', default=''),
            'secret': config('GOOGLE_CLIENT_SECRET', default=''),
        }
    },
    'microsoft': {
        'SCOPE': [
            'User.Read',
        ],
        'APP': {
            'client_id': config('MICROSOFT_CLIENT_ID', default=''),
            'secret': config('MICROSOFT_CLIENT_SECRET', default=''),
        }
    }
}

# REST Auth Configuration
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
    'JWT_AUTH_COOKIE': 'auth-token',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh-token',
    'JWT_AUTH_SECURE': False,  # True em produção com HTTPS
    'JWT_AUTH_SAMESITE': 'Lax',
    'SESSION_AUTHENTICATION': False,
    'USER_DETAILS_SERIALIZER': 'core.serializers.UserSerializer',
    'JWT_SERIALIZER': 'core.serializers.CustomJWTSerializer',
}

# Configurações adicionais para JWT
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'auth-token'
JWT_AUTH_REFRESH_COOKIE = 'refresh-token'
JWT_AUTH_HTTPONLY = False

# =============================================================================
# GOOGLE OAUTH CONFIGURATION
# =============================================================================
# Nota: Railway usa GOOGLE_CLIENT_ID, mas settings precisa de GOOGLE_OAUTH_CLIENT_ID
GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default='')

# =============================================================================
# MEDIA FILES CONFIGURATION (for certificates and logos)
# =============================================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# MERCADO PAGO CONFIGURATION (for payments and subscriptions)
# =============================================================================
MERCADOPAGO_ACCESS_TOKEN = config('MERCADOPAGO_ACCESS_TOKEN', default='')
MERCADOPAGO_PUBLIC_KEY = config('MERCADOPAGO_PUBLIC_KEY', default='')

# URLs para redirect e notificações
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')
BACKEND_URL = config('BACKEND_URL', default='http://localhost:8000')
