# Generated by Django 5.2.7 on 2025-11-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Empresa'),
        ),
    ]
