# Generated by Django 5.2.7 on 2025-11-14 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
        ('customers', '0002_alter_customer_last_visit'),
        ('pos', '0002_alter_cashregister_tenant_alter_sale_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', '-date'], name='pos_sale_tenant__6104cd_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'payment_status', '-date'], name='pos_sale_tenant__61e11c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'payment_method', '-date'], name='pos_sale_tenant__6cda09_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cash_register', '-date'], name='pos_sale_cash_re_32a10a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', '-date'], name='pos_sale_custome_605b4b_idx'),
        ),
    ]
