# Generated by Django 5.2.7 on 2025-10-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="last_visit",
            field=models.DateField(
                blank=True,
                help_text="Data da última visita (atualizado automaticamente)",
                null=True,
                verbose_name="Última Visita",
            ),
        ),
    ]
