# Generated by Django 5.2.7 on 2025-11-03 19:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Equipe')], default='individual', max_length=20, verbose_name='Tipo')),
                ('target_type', models.CharField(choices=[('revenue', 'Faturamento'), ('sales_count', 'Quantidade de Vendas'), ('services_count', 'Quantidade de Serviços'), ('products_sold', 'Produtos Vendidos'), ('new_customers', 'Novos Clientes')], max_length=20, verbose_name='Tipo de Meta')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor Alvo')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor Atual')),
                ('period', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Período')),
                ('start_date', models.DateField(verbose_name='Data Início')),
                ('end_date', models.DateField(verbose_name='Data Fim')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('failed', 'Falhada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, help_text='Deixe vazio para meta de equipe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'goals_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor')),
                ('percentage', models.FloatField(verbose_name='Porcentagem')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_history', to='goals.goal', verbose_name='Meta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Progresso da Meta',
                'verbose_name_plural': 'Progresso das Metas',
                'db_table': 'goals_progress',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['tenant', 'status'], name='goals_goal_tenant__25fe95_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['tenant', 'user'], name='goals_goal_tenant__c8f2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['start_date', 'end_date'], name='goals_goal_start_d_825b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='goalprogress',
            index=models.Index(fields=['goal', 'date'], name='goals_progr_goal_id_c3b569_idx'),
        ),
    ]
