# Generated by Django 5.2.7 on 2025-10-16 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("customers", "0002_alter_customer_last_visit"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="customers.customer",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço cobrado por este agendamento específico",
                max_digits=10,
                null=True,
                verbose_name="Preço Cobrado",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["tenant", "customer"], name="scheduling__tenant__f4152b_idx"
            ),
        ),
    ]
