# Generated by Django 5.2.7 on 2025-10-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("servico", "Serviço"),
                    ("produto", "Produto"),
                    ("salario", "Salário"),
                    ("aluguel", "Aluguel"),
                    ("fornecedor", "Fornecedor"),
                    ("imposto", "Imposto"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
    ]
