# Generated by Django 5.2.7 on 2025-10-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('barbeiro', 'Barbeiro'), ('caixa', 'Caixa'), ('atendente', 'Atendente'), ('superadmin', 'Super Administrador')], default='atendente', max_length=20, verbose_name='Função'),
        ),
    ]
