# Generated by Django 5.2.7 on 2025-11-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_zipcode',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='certificate_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Certificado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='certificate_password',
            field=models.CharField(blank=True, help_text='Armazenado criptografado', max_length=255, verbose_name='Senha do Certificado'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='digital_certificate',
            field=models.FileField(blank=True, help_text='Arquivo .pfx do certificado A1', null=True, upload_to='tenants/certificates/', verbose_name='Certificado Digital (.pfx)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Cor Primária'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='state_registration',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Google Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Google ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, verbose_name='Foto de Perfil'),
        ),
    ]
