# Generated by Django 5.2.7 on 2025-11-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='current_clients_count',
            field=models.IntegerField(default=0, help_text='Contador de clientes ativos (limite: 10 no trial)', verbose_name='Total de Clientes'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_services_count',
            field=models.IntegerField(default=0, help_text='Contador de serviços cadastrados (limite: 4 no trial)', verbose_name='Total de Serviços'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mp_subscription_id',
            field=models.CharField(blank=True, help_text='ID da assinatura no Mercado Pago', max_length=255, null=True, verbose_name='ID da Assinatura MP'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_id',
            field=models.CharField(blank=True, help_text='Referência ao plano escolhido (basico/profissional/premium)', max_length=50, null=True, verbose_name='ID do Plano'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial - Período de Teste'), ('ACTIVE', 'Ativo'), ('PAST_DUE', 'Pagamento Atrasado'), ('CANCELED', 'Cancelado')], default='TRIAL', help_text='Status atual da assinatura do tenant', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora exata que o período de teste acaba (7 dias)', null=True, verbose_name='Trial termina em'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('profissional', 'Profissional'), ('premium', 'Premium')], default='basico', max_length=20, verbose_name='Plano'),
        ),
    ]
